acid/ContactBook/config/routes.rb
Demo2::Application.routes.draw do
  resources :contacts

  resources :companies
  
  get "home/index"

  root :to=> "home#index"
  

end

acid/ContactBook/app/models/company.rb
class Company < ActiveRecord::Base
  attr_accessible :adress, :name
attr_accessible :email, :first_name, :last_name, :phone_numer
  validates :name, :presence=>true

  def self.search(search)
	  if search
	    find(:all, :conditions => ['name LIKE ?', "%#{search}%"])
	  else
	    find(:all)
	  end
	end

end

acid/ContactBook/app/models/contact.rb
class Contact < ActiveRecord::Base
  belongs_to :company
  attr_accessible :company_id, :email_adress, :first_name, :last_name, :phone_numer, :photo, :tweet_user

  validates :first_name, :presence=>true
  validates :email_adress, :format => { :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/, :on => :create, :on => :update }
  validates :phone_numer, :format => { :with => /44+([0-9]{3,})+[0-9]{6,}/, :on => :create , :on => :update}

    #Thumbnail
  has_attached_file :photo,
     :styles => {
       :thumb=> "70x70#",
       :small  => "250x250>",
       :medium  => "400x400>" },
       :default_url => "/photos/missing.png"

validates_attachment_size :photo, :less_than => 3.megabytes
validates_attachment_content_type :photo, :content_type => ['image/jpeg','image/jpg', 'image/png'], :message => "only pngs and jpgs are allowed with less than 3 Mb."

	def self.search(search)
	  if search
	    find(:all, :conditions => ['first_name LIKE ?', "%#{search}%"])
	  else
	    find(:all)
	  end
	end


end

acid/ContactBook/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

acid/ContactBook/app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  # GET /companies
  # GET /companies.json
  def index

      @companies = Company.search(params[:search])

    # @companies = Company.all

    # respond_to do |format|
    #   format.html # index.html.erb
    #   format.json { render json: @companies }
    # end
  end

  # GET /companies/1
  # GET /companies/1.json
  def show
    @company = Company.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @company }
    end
  end

  # GET /companies/new
  # GET /companies/new.json
  def new
    @company = Company.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @company }
    end
  end

  # GET /companies/1/edit
  def edit
    @company = Company.find(params[:id])
  end

  # POST /companies
  # POST /companies.json
  def create
    @company = Company.new(params[:company])

    respond_to do |format|
      if @company.save
        format.html { redirect_to @company, notice: 'Company was successfully created.' }
        format.json { render json: @company, status: :created, location: @company }
      else
        format.html { render action: "new" }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /companies/1
  # PUT /companies/1.json
  def update
    @company = Company.find(params[:id])

    respond_to do |format|
      if @company.update_attributes(params[:company])
        format.html { redirect_to @company, notice: 'Company was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    @company = Company.find(params[:id])
    @company.destroy

    respond_to do |format|
      format.html { redirect_to companies_url }
      format.json { head :no_content }
    end
  end
end

acid/ContactBook/app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  # GET /contacts
  # GET /contacts.json


  def index

    
  @contacts = Contact.search(params[:search])

    # @contacts = Contact.all

    # respond_to do |format|
    #   format.html # index.html.erb
    #   format.json { render json: @contacts }
    # end
  end

  # GET /contacts/1
  # GET /contacts/1.json
  def show
    @contact = Contact.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @contact }
    end
  end

  # GET /contacts/new
  # GET /contacts/new.json
  def new
    @contact = Contact.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @contact }
    end
  end

  # GET /contacts/1/edit
  def edit
    @contact = Contact.find(params[:id])
  end

  # POST /contacts
  # POST /contacts.json
  def create

      #Borrado por parecer inncesario @Contact = Contact.create( params[:user] )



    @contact = Contact.new(params[:contact])

    respond_to do |format|
      if @contact.save
        format.html { redirect_to @contact, notice: 'Contact was successfully created.' }
        format.json { render json: @contact, status: :created, location: @contact }
      else
        format.html { render action: "new" }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /contacts/1
  # PUT /contacts/1.json
  def update
    @contact = Contact.find(params[:id])

    respond_to do |format|
      if @contact.update_attributes(params[:contact])
        format.html { redirect_to @contact, notice: 'Contact was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1
  # DELETE /contacts/1.json
  def destroy
    @contact = Contact.find(params[:id])
    @contact.destroy

    respond_to do |format|
      format.html { redirect_to contacts_url }
      format.json { head :no_content }
    end
  end
end

acid/ContactBook/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

acid/ContactBook/app/helpers/application_helper.rb
module ApplicationHelper
end

acid/ContactBook/app/helpers/companies_helper.rb
module CompaniesHelper
end

acid/ContactBook/app/helpers/contacts_helper.rb
module ContactsHelper
end

acid/ContactBook/app/views/companies/_form.html.erb
<%= form_for(@company) do |f| %>
  <% if @company.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@company.errors.count, "error") %> prohibited this company from being saved:</h2>

      <ul>
      <% @company.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :adress %><br />
    <%= f.text_field :adress %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

acid/ContactBook/app/views/companies/edit.html.erb
<h1>Editing company</h1>

<%= render 'form' %>

<%= link_to 'Show', @company %> |
<%= link_to 'Back', companies_path %>

acid/ContactBook/app/views/companies/index.html.erb
<h1>Listing companies</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Adress</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @companies.each do |company| %>
  <tr>
    <td><%= company.name %></td>
    <td><%= company.adress %></td>
    <td><%= link_to 'Show', company %></td>
    <td><%= link_to 'Edit', edit_company_path(company) %></td>
    <td><%= link_to 'Destroy', company, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<!-- Form for searchs -->
<%= form_tag companies_path, :method => 'get' do %>
  <p>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Search by name company", :name => nil %>
  </p>
<% end %>

<%= link_to 'New Company', new_company_path %>
<%= link_to "Show all companies", companies_path %>
<%= link_to "Show contacts directory", contacts_path %>

acid/ContactBook/app/views/companies/new.html.erb
<h1>New company</h1>

<%= render 'form' %>

<%= link_to 'Back', companies_path %>

acid/ContactBook/app/views/companies/show.html.erb
<p id="notice"><%= notice %></p>

<h1>Company <%= @company.name %> Details</h1>

<p>
  <b>Name:</b>
  <%= @company.name %>
</p>

<p>
  <b>Adress:</b>
  <%= @company.adress %>
</p>
<p>
  <b>Contacts:</b>
  <% @mostrar=Contact.where(:company_id=>@company.id) %>
  <% @mostrar.each do |contact| %>
  <%= link_to contact.first_name+' '+contact.last_name ,contact%>
  <% end %>
</p>

<%= link_to 'Edit', edit_company_path(@company) %> |
<%= link_to 'Back', companies_path %>

acid/ContactBook/app/views/contacts/_form.html.erb
<%= form_for(@contact) do |f| %>
  <% if @contact.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@contact.errors.count, "error") %> prohibited this contact from being saved:</h2>

      <ul>
      <% @contact.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<p>
  <%= f.label 'Photo' %><br />
  <%= f.file_field :photo %>
</p>

  <div class="field">
    <%= f.label :first_name %><br />
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br />
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :email_adress %><br />
    <%= f.text_field :email_adress %>
  </div>
  <div class="field">
    <%= f.label :phone_numer %><br />
    <%= f.text_field :phone_numer %>
  </div>
  <div class="field">
    <%= f.label :tweet_user %><br />
    <%= f.text_field :tweet_user %>
  </div>
  <div class="field">
    <%= f.label :company %><br />
    <%= f.collection_select :company_id, Company.order('name ASC').all, :id, :name, :include_blank => true %>
<!--     <%= f.collection_select :company_id, Company.all, :id, :name%>
 -->  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

acid/ContactBook/app/views/contacts/edit.html.erb
<h1>Editing contact</h1>


<%= render 'form' %>

<%= link_to 'Show', @contact %> |
<%= link_to 'Back', contacts_path %>

acid/ContactBook/app/views/contacts/index.html.erb
<h1>Listing contacts</h1>

<table>
  <tr>
    <th>Photo </th>
    <th>First name</th>
    <th>Last name</th>
    <th>Email adress</th>
    <th>Phone numer</th>
    <th>Company</th>
    <th>Options</th>
    
  </tr>

<% @contacts.each do |contact| %>
  <tr>

    <td><%= image_tag contact.photo.url(:thumb) unless contact.photo.nil? %></td>
    <td><%= contact.first_name %></td>
    <td><%= contact.last_name %></td>
    <td><%= contact.email_adress %></td>
    <td><%= contact.phone_numer %></td>
    <td>
        <% if contact.company==nil %>
            <%='No company added yet' %>
         <% else %> 
         <%= link_to contact.company.name,contact.company%>
        <% end %>
    </td>
    <td><%= link_to 'Show', contact %> 
      <%= link_to 'Edit', edit_contact_path(contact) %>
      <%= link_to 'Destroy', contact, method: :delete, data: { confirm: 'Are you sure?' } %>
    </td>
  </tr>
<% end %>
</table>

<br />

<!-- Form for searchs -->
<%= form_tag contacts_path, :method => 'get' do %>
  <p>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Search by first name", :name => nil %>
  </p>
<% end %>

<%= link_to 'New Contact', new_contact_path %> 
<%= link_to "Show all contacts", contacts_path %>
<%= link_to "Show companies directory", companies_path %>

acid/ContactBook/app/views/contacts/new.html.erb
<h1>New contact</h1>



<%= render 'form' %>

<%= link_to 'Back', contacts_path %>

acid/ContactBook/app/views/contacts/show.html.erb
<p id="notice"><%= notice %></p>

<h1>Contact <%= @contact.first_name %> Details</h1>

<p>
  <h2>Photo</h2>
  
<%= image_tag @contact.photo.url(:small) unless @contact.photo.nil? %>

<!--  <%= image_tag @contact.photo.url(:thumb) unless @contact.photo.nil? %> -->
</p>

<p>
  <b>First name:</b>
  <%= @contact.first_name %>
</p>

<p>
  <b>Last name:</b>
  <%= @contact.last_name %>
</p>

<p>
  <b>Email adress:</b>
  <%= @contact.email_adress %>
</p>

<p>
  <b>Phone numer:</b>
  <%= @contact.phone_numer %>
</p>

<p>
  <b>Company:</b>
  <% if @contact.company==nil %>
<em>No company added yet</em>
 <% else %> 
 <%= link_to @contact.company.name,@contact.company%>
<% end %>

</p>
<p>
  <b>Tweet User:</b>
  <%= @contact.tweet_user unless @contact.tweet_user.nil? %>
</p>
<p>
  <b>Lasts Tweet:</b>
  <br>
 <% if @contact.tweet_user.blank? %>
    <em>No tweeter user added yet</em>
 <% else %> 
 <% if  !Twitter.user?(@contact.tweet_user) %>
 <em>Invalid tweeter user</em>
 <% else %> 
    <% @tweet=Twitter.user_timeline(@contact.tweet_user).first%>
    <% @tweet2=Twitter.user_timeline(@contact.tweet_user).second %>
    <% @tweet3=Twitter.user_timeline(@contact.tweet_user).third %>
    <% @tweet4=Twitter.user_timeline(@contact.tweet_user).fourth %>
  <% end %>
    <p>
    <strong>
    <%= '#'+@tweet.created_at.to_s.slice(0..19) +'-- '+@tweet.text unless @tweet.nil?%><br />
    <%= '#'+@tweet2.created_at.to_s.slice(0..19) +'-- '+@tweet2.text unless @tweet.nil?%><br />
    <%= '#'+@tweet3.created_at.to_s.slice(0..19) +'-- '+@tweet3.text unless @tweet.nil?%><br />
    <%= '#'+@tweet4.created_at.to_s.slice(0..19) +'-- '+@tweet4.text unless @tweet.nil?%><br />
    </strong>
    </p>
  <% end %>
  
  
  
  </br>
  
</p>


<%= link_to 'Edit', edit_contact_path(@contact) %> |
<%= link_to 'Back', contacts_path %>

acid/ContactBook/app/views/home/index.html.erb
<h1>Welcome to the new and creative contact book</h1>
<h3>
	<%= link_to "Agenda -> Contacts", contacts_path %>
</h3>
<h3>
<%= link_to "Agenda -> Companies", companies_path %>
</h3>

acid/ContactBook/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Demo2</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>